MVCProject/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCProject.Data.Services;
using MVCProject.Data.Models;

namespace MVCProject.Controllers
{
    public class MenuController : Controller
    {
        IMenuService mMenuService;

        public MenuController(IMenuService menuService)
        {
            mMenuService = menuService;
        }
        
        [ChildActionOnly]
        public ActionResult Index()
        {
            List<MenuModel> menus = mMenuService.GetPrimaryMenus();
            MenuListModel menuList = new MenuListModel(menus);
          
            return PartialView(menuList);

        }
    }
}

MVCProject/Views/Shared/Error404.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "404";
}

<h1 class="text-danger">Page Not Found.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
             @Html.Action("Index", "Menu")
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AngularMVCApp")
    @RenderSection("scripts", required: false)
</body>
</html>